### ISSUE TITLE
Pagination titles 

### ISSUE THREAD

**Issue by bmxmiko** [ianwitherow/react-filterable-table#9]
Hello,
Is there any option to set titles of pagination ? I mean "Last", "First"

**Comment by ianwitherow** [comment]
Sorry for not getting back to you earlier. Currently there isn't really a good way to do that, but I could make it so that you can pass in some Pager settings for the component to use (it's just using this component for paging: https://github.com/AZaviruha/pager)

I'll take a look when I get a minute!
